### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by askfriends** [HasibulKabir/heroku-buildpack-rarlab#2]
Hi;
iam new to all this, never used heroku buildpacks before, so i am little confused here.
I am running a telegram bot hosted on heroku to download torrents to my td, now i want to add rar/unrar feature to that bot, so that i may make rar/unrar and also make split parts to large files.

So will you guide me to make it work?

Now i should run this command after loggin-in in heroku cli to install it?
heroku config:add BUILDPACK_URL=git://github.com/HasibulKabir/heroku-buildpack-rarlab.git"

and after that how can i use unrar/rar command to make a file/folder .rar?

**Comment by HasibulKabir** [comment]
command: `heroku buildpacks:set github.com/HasibulKabir/heroku-buildpack-rarlab.git`

Run this command from heroku cli. 

Now create a release build for your heroku app. [Just deploy new version]

Now run `rar` or `unrar` to get usage.

Alternatively you can check this links too. 
[RAR](https://del.dog/igabapegar)
[UNRAR](https://del.dog/isewovilil)

**Comment by askfriends** [comment]
> command: `heroku buildpacks:set github.com/HasibulKabir/heroku-buildpack-rarlab.git`
> 
> Run this command from heroku cli.
> 
> Now create a release build for your heroku app. [Just deploy new version]
> 
> Now run `rar` or `unrar` to get usage.
> 
> Alternatively you can check this links too.
> [RAR](https://del.dog/igabapegar)
> [UNRAR](https://del.dog/isewovilil)

i did that, but rar or unrar is not working.

**Comment by HasibulKabir** [comment]
please use website and add this repo url as buildpack from app settings. Now deploy new version.

 If still not working please contact me on Telegram https://t.me/HasibulKobir

**Comment by askfriends** [comment]
> please use website and add this repo url as buildpack from app settings. Now deploy new version.
> 
> If still not working please contact me on Telegram https://t.me/HasibulKobir

ok, i have sent you msg on tg

**Comment by HasibulKabir** [comment]
According to message on Telegram, it's not problem with my code. So closing this issue.
